grassmunk/Chicago95

- Extras/Chicago95.zsh-theme
- C prompt by default
- F prompt if the previous command had an exit code other than 0
- G prompt when in a git repository, followed by the branch name (in yellow) and the status (dirty in red, clean in green)
> Add a dos inspired theme for oh-my-zsh

- Plymouth/Chicago95/Chicago95.plymouth
- Plymouth/Readme.md
In version 0.9.2 of Plymouth, the path to themes was changed from /lib/plymouth/themes/ to /usr/share/plymouth/themes/.
https://launchpad.net/ubuntu/+source/plymouth/0.9.2-3ubuntu1
I updated the scripts and Readme to reflect these changes and also added the installation of plymouth-themes to the Readme.
> Plymouth fixes for Ubuntu 16.04+

- Lightdm/Chicago95/README.md
\#\# is not supported when combined with ====. Or rather, it works, but the header has a literal # in it.
> Lightdm/README.md: fix headers

- Theme/Chicago95/gtk-3.0/gtk-widgets.css
Most bars seem to look like this in gtk3:
In case you are wondering: these bars are notification area (network manager), 2x network monitor, 2x network monitor, disk performance monitor, free space checker, free space checker, disk performance monitor, 3x system load monitor, sensor plugin, battery monitor, timer
> Fix panel progressbars

- Icons/Chicago95-tux/apps/48/Verknüpfung mit simple-scan.png
- Icons/Chicago95/apps/48/Verknüpfung mit simple-scan.png
This is needed to run `gtk-update-icon-cache Icons/Chicago95/` without errors
> Remove icon preventing cache creation, fix #61

- Lightdm/Chicago95/js/main.js
They are not displayed anyway, so dont try to initalize them which currently produces an error message. Fixes #66.
Specifically: The code contains code for links for suspend, shutdown and reboot actions. The container where they are meant to be put into is missing in index.html though. Was the webkit greeter supposed to have those actions like paddy-greeter ([image](https://camo.githubusercontent.com/7b133ebfb095abe372686a9ca433ac4088168dba/68747470733a2f2f7261772e6769746875622e636f6d2f6b616c6d616e6f6c61682f70616464792d677265657465722f6d61737465722f73637265656e73686f742e706e67)) has? If that is the case, I could further modify it but dont really know where to put those. [The actual login screen](https://duckduckgo.com/?q=win+95+login+screen&t=ffab&iax=images&ia=images) (different than the …
> Do not call initializeActions()

- Theme/Chicago95/gtk-3.0/gtk.css
The GTK 3 panel icons are now black instead of white.
> Adding missing panel_fg_color definition

- Icons/Chicago95/apps/scalable/nautilus.svg
- Icons/Chicago95/apps/scalable/org.gnome.Nautilus.svg
Add symlinks for newer versions of gnome-shell to render the nautilus icon properly
> Add Nautilus Icons for Gnome-Shell

- Extras/99-ms-sans-serif-bold.conf
- INSTALL.md
The previous method for using MS Sans Serif with Chicago95 did not produce a working bold font.  The updated instructions now allow the bold font to be used (in the window title, etc).  This is done by using the bitmapped version of the MS Sans Serif font converted to TrueType in conjunction with the newer "Microsoft Sans Serif" font.
> Add instructions and fontconfig for MS Sans Serif Bold

- .gitignore
- Makefile
- sounds/chicago95-startup.desktop
Improve makefile. Add verbs install_sounds and install_plus. Remove verb install_greeter
Add support for variable use_underscores for debuild which really struggles with spaces in deployed filenames.
> Deployment fixes

- INSTALL.md
Add commands in INSTALL.md to set GDK scale for HiDPI users. This change makes most apps run with full HiDPI support, giving properly scaled buttons, scrollbars, and other UI elements. It makes the theme very close to full HiDPI support.
> Set HiDPI GDK scale

- Theme/Chicago95/xfwm4/themerc
- Theme/Chicago95/xfwm4_hidpi/themerc
창 최대화 시 상단 보더가 숨겨지지 않는 문제를 해결합니다.
This solves the problem that the top window border won't disappear when maximized.
https://imgur.com/a/4TLOWLd ==> https://imgur.com/a/l6e5bs1
https://imgur.com/a/NoDejo3 (HiDPI support)
https://imgur.com/a/HTAYYrk (Original Windows 95 just for comparison)
> adjusting frame_border_top

- Plymouth/Chicago95/Chicago95.script
- Plymouth/Readme.md
Improved performance for Plymouth Chicago95 theme, now it uses ~15% of CPU instead of ~60% before.
Updated README with installation instruction for Arch Linux.
> Plymouth theme update

- Icons/Chicago95-tux/apps/16/google-chrome-unstable.svg
- Icons/Chicago95-tux/apps/22/google-chrome-unstable.svg
- Icons/Chicago95-tux/apps/24/google-chrome-unstable.svg
- Icons/Chicago95-tux/apps/256/google-chrome-unstable.svg
- Icons/Chicago95-tux/apps/32/google-chrome-unstable.svg
- Icons/Chicago95-tux/apps/48/google-chrome-unstable.svg
- Icons/Chicago95-tux/apps/scalable/google-chrome-unstable.svg
- Icons/Chicago95/apps/scalable/google-chrome-unstable.svg
I don't know if you want to introduce a new icon for the dev version of Chrome, but I figured I could at least add a link to the existing logo.
> Add link to logo of Google Chrome (unstable)

- README.md
The link was referring to `Readme.md`(in lower case), which resulted in a 404 error.
> Fixes Plymouth link on README.md

- Plymouth/Chicago95/Chicago95.script
Make password promt and message visible. Move message under Windows 95
title and set orange color like shutting down message have.
Signed-off-by: Dmytro Kropenko <k.dmitriu@gmail.com>
> plymouth: Update password promt and message

- Theme/Chicago95/gtk-3.0/apps/xfce.css
Currently, the background of desktop item names are drawn with a lot of extra padding.
However, using the `background-image` property with a single color `-gtk-gradient`, we can reposition & resize the background to trim off some of this padding & make the rendering appear closer to the original.
This is untested on high-DPI, so if anyone has a high-DPI system to test this with, please let me know how it goes.
Thank you for your time!
> GTK hack to draw the background of desktop item names more like the original

- Theme/Chicago95/xfce-notify-4.0/gtk.css
Since we use solid border, we dont really need box shadow, also this PR fix weird shadow border for xfce notification as in the picture below 
- OS: Xubuntu 22.04
- XFCE 4.16
**Before**
weird shadow on the bottom right
**After**
> remove box shadow that make weird border for xfce notifications

- Icons/Chicago95-tux/apps/scalable/redshift-status-off.svg
- Icons/Chicago95-tux/apps/scalable/redshift-status-on.svg
- Icons/Chicago95/apps/scalable/redshift-status-off.svg
- Icons/Chicago95/apps/scalable/redshift-status-on.svg
I use Redshift-gtk for my dark mode. It bugged me for the longest time that its icons did not match the theme (as Chicago does not have the icons for them), so using the Windows 95 color palette, I created them. I have been using them a while and like the look a lot better.
> Add thematically appropriate Redshift icons

- Theme/Chicago95/gtk-3.0/apps/whiskermenu.css
The color can be especially seen with dark themes. Users may also have different fonts other than Helvetica or MS Sans Serif, like Tahoma or Arial.
> Remove hardcoded color and fonts in Whisker Menu

- README.md
Clear up the confusion from #309 by removing instructions to install outdated apt packages from a stale fork.
> Remove outdated apt package instructions

- KDE/SDDM/Chicago95/main.qml
Right now, the SDDM theme uses size 12 "Sans" font in most places and size 12 Liberation Sans in one spot. This PR changes all of these instances to be size 8 Helvetica, as used by other parts of Chicago95. The SDDM theme tarball is unchanged and will need to be updated.
> SDDM theme font fixes

- Icons/Chicago95/status/symbolic/audio-volume-high-symbolic.png
- Icons/Chicago95/status/symbolic/audio-volume-high.png
- Icons/Chicago95/status/symbolic/audio-volume-low-symbolic.png
- Icons/Chicago95/status/symbolic/audio-volume-low.png
- Icons/Chicago95/status/symbolic/audio-volume-medium-symbolic.png
- Icons/Chicago95/status/symbolic/audio-volume-medium.png
- Icons/Chicago95/status/symbolic/audio-volume-muted-symbolic.png
- Icons/Chicago95/status/symbolic/audio-volume-muted.png
- Icons/Chicago95/status/symbolic/audio-volume-off-symbolic.png
Changing the volume level sends a notification with a broken icon in XFCE. These volume icons need to be in the symbolic directory to be registered with the notification daemon.
> Fix volume changed icon for xfce4-notifyd

- Plymouth/Chicago95/Chicago95.script
- Plymouth/README.md
Changes the font for password prompts and other Plymouth messages to Helvetica Bold 18, similar to my other recent PR that changed the SDDM theme to Helvetica.
> Font improvements in W95 Plymouth theme

- Theme/Chicago95/gtk-3.0/apps/xfce-panel-hacks.css
Tasklist icon sizes have been reworked in Xfce 4.20 and the default size is larger than it was in Xfce 4.18. I believe 0.8 scaling is the closest to the look in Xfce 4.18.
Tasklist icon size with no scaling in Xfce 4.20:
Scaling factor 0.9:
Scaling factor 0.8:
Scaling factor 0.75:
(upstreaming https://github.com/winblues/blue95/pull/52)
> Reduce size of tasklist icons for Xfce 4.20
